name: Deploy
on:
  push:
    branches: [ main ]   

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: "Build and Test"
        run: |
          dotnet build
          dotnet test
  version:
    needs: test
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.newversion.outputs.version }}
      tag: ${{ steps.newversion.outputs.tag }}      
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set New Version
      id: newversion
      shell: pwsh
      run: |
            $currentVersion = git describe --abbrev=0 --tags --match "v.[0-9]*.[0-9]*.[0-9]*-Release"

            if ($currentVersion -ne $null) {
              $v = $currentVersion.Split('-')[0].TrimStart('v', '.')
              Write-Output "RELEASE: New Version: $($v)"
              Write-Output "version=$($v)" >> $Env:GITHUB_OUTPUT
              Write-Output "tag=$($currentVersion)" >> $Env:GITHUB_OUTPUT
            } else {
    
                $currentVersion = git describe --abbrev=0 --tags --match "v.[0-9]*.[0-9]*.[0-9]*" 
                $versionParts = $currentVersion.Split('-')
                $v = $versionParts[0]
                $increment = 1

                $vparts = $v.Split('.')
                $vparts = $vparts | Where-Object { $_ -ne 'v' -and $_ -ne '' }
                $vparts[2] = "$([int]$vparts[2] + [int]$increment)"
                $v = $vparts -join '.'
                Write-Output "New Version: $($v)"
                Write-Output "version=$($v)" >> $Env:GITHUB_OUTPUT
                Write-Output "tag=" >> $Env:GITHUB_OUTPUT
            }
  prepublish:
      needs: [test, version]
      runs-on: ubuntu-latest
      outputs:
        description: ${{ steps.meta.outputs.description }}
        changeinfo: ${{ steps.meta.outputs.changeinfo }}
      steps:
      - name: Checkout Sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name : Get Meta Data
        shell: pwsh
        id: meta
        run: |
          [xml]$xml = get-content "src/AspNetCore.MailKitMailer/AspNetCore.MailKitMailer.csproj"    
          $description = $xml.SelectSingleNode("//Description").InnerText;
          $changes = $xml.SelectSingleNode("//PackageReleaseNotes").InnerText;
          Write-Output "description=$($description.Trim().Replace("`t", '') | ConvertTo-Json)" >> $Env:GITHUB_OUTPUT
          Write-Output "changeinfo=$($changes.Trim().Replace("`t", '') | ConvertTo-Json)" >> $Env:GITHUB_OUTPUT

  publish:
      needs: [test, version, prepublish]
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Checkout Sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create Package
        run: |
          dotnet build src/AspNetCore.MailKitMailer/AspNetCore.MailKitMailer.csproj -c Release -p:AssemblyVersion=${{ needs.version.outputs.version }} -p:PackageVersion=${{ needs.version.outputs.version }}
          dotnet pack src/AspNetCore.MailKitMailer/AspNetCore.MailKitMailer.csproj -c Release -p:AssemblyVersion=${{ needs.version.outputs.version }} -p:PackageVersion=${{ needs.version.outputs.version }} --output nget_pkg
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.version.outputs.version }}
          name: Release v${{ needs.version.outputs.version }}
          body: |
           # Release Info Version ${{ needs.version.outputs.version  }}
           ## Info
           ${{fromJSON(needs.prepublish.outputs.description)}}
           ## Changes in v${{ needs.version.outputs.version  }}
           ${{fromJSON(needs.prepublish.outputs.changeinfo)}}
          draft: false
          prerelease: false
          files: |
            ./nget_pkg/AspNetCore.MailKitMailer.${{ needs.version.outputs.version }}.nupkg
            src/AspNetCore.MailKitMailer/bin/Release/net10.0/AspNetCore.MailKitMailer.dll
      - name: Delete Release Tag
        if: ${{ needs.version.outputs.tag }}
        run: git push --delete origin ${{ needs.version.outputs.tag }}
      - name: Publish package to nuget
        run: dotnet nuget push  "nget_pkg/AspNetCore.MailKitMailer.${{ needs.version.outputs.version }}.nupkg" -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json  
