name: Release 1.1.x

on:
  push:
    branches: [ release-1.1.x ]
  pull_request:
    branches: [ release-1.1.x ]
    

jobs:
  
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Version Number
        shell: pwsh
        run: | 
          $foo = "bar" |
          Write-Host "::set-output name=version::$($foo)"
      - name: Print Version
        run: echo '${{ steps.v.outputs.version }}'
