name: Release 1.1.x

on:
  push:
    branches: [ release-1.1.x ]
  pull_request:
    branches: [ release-1.1.x ]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Version Number
        uses: paulhatch/semantic-version@v4.0.2
        id: v
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "1.1.${increment}"
          # Indicate whether short tags like 'v1' should be supported. If false only full
          # tags like 'v1.0.0' will be recognized.
          short_tags: true
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: true
      - name: Print Version
        run: 'echo "${{ steps.v.outputs.version }}"' 
      - name: Print Version Tag
        run : 'echo "${{ steps.v.outputs.tag }}"
