name: Release 1.1.x

on:
  push:
    branches: [ release-1.1.x ]
  pull_request:
    branches: [ release-1.1.x ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Version
      uses: paulhatch/semantic-version@v4.0.2
      id: pkg-v
    - name: Print Version
      run: echo '${{ steps.pkg-v.outputs.version }}'
